// Poetry for Neanderthals — the deck.
// Each card has a short "top" word worth +1, contained inside the full
// "phrase" worth +3. The challenge: describe both using only one-syllable
// clue words.
const DECK = {
  "Movies & Shows": [
    { top: "Wars", phrase: "Star Wars" },
    { top: "Park", phrase: "Jurassic Park" },
    { top: "King", phrase: "The Lion King" },
    { top: "Alone", phrase: "Home Alone" },
    { top: "Story", phrase: "Toy Story" },
    { top: "Woman", phrase: "Wonder Woman" },
    { top: "Nemo", phrase: "Finding Nemo" },
    { top: "Potter", phrase: "Harry Potter" },
    { top: "Tank", phrase: "Shark Tank" },
    { top: "Tales", phrase: "Duck Tales" },
    { top: "Age", phrase: "Ice Age" },
    { top: "Willy", phrase: "Free Willy" },
    { top: "Man", phrase: "Spider Man" },
    { top: "Mission", phrase: "Mission Impossible" },
    { top: "Panda", phrase: "Kung Fu Panda" },
    { top: "Kid", phrase: "The Karate Kid" },
    { top: "Strange", phrase: "Doctor Strange" },
    { top: "University", phrase: "Monsters University" },
    { top: "Race", phrase: "The Amazing Race" },
    { top: "Idol", phrase: "American Idol" },
    { top: "Future", phrase: "Back to the Future" },
    { top: "Furious", phrase: "Fast and Furious" },
    { top: "Apes", phrase: "Planet of the Apes" },
    { top: "Dead", phrase: "The Walking Dead" },
    { top: "Bad", phrase: "Breaking Bad" },
    { top: "Thrones", phrase: "Game of Thrones" },
    { top: "Things", phrase: "Stranger Things" },
    { top: "Theory", phrase: "The Big Bang Theory" },
    { top: "Blinders", phrase: "Peaky Blinders" },
    { top: "Prince", phrase: "The Fresh Prince" },
    { top: "Beast", phrase: "Beauty and the Beast" },
    { top: "Mermaid", phrase: "The Little Mermaid" },
    { top: "Beauty", phrase: "Sleeping Beauty" },
    { top: "White", phrase: "Snow White" },
    { top: "Pan", phrase: "Peter Pan" }
  ],
  "Food & Drink": [
    { top: "Cheese", phrase: "Grilled Cheese" },
    { top: "Dog", phrase: "Hot Dog" },
    { top: "Fries", phrase: "French Fries" },
    { top: "Cream", phrase: "Ice Cream" },
    { top: "Butter", phrase: "Peanut Butter" },
    { top: "Pie", phrase: "Apple Pie" },
    { top: "Beer", phrase: "Root Beer" },
    { top: "Cake", phrase: "Birthday Cake" },
    { top: "Candy", phrase: "Cotton Candy" },
    { top: "Rice", phrase: "Fried Rice" },
    { top: "Bread", phrase: "Banana Bread" },
    { top: "Juice", phrase: "Orange Juice" },
    { top: "Chips", phrase: "Potato Chips" },
    { top: "Soup", phrase: "Chicken Soup" },
    { top: "Milk", phrase: "Chocolate Milk" },
    { top: "Steak", phrase: "Grilled Steak" },
    { top: "Syrup", phrase: "Maple Syrup" },
    { top: "Donut", phrase: "Glazed Donut" },
    { top: "Pizza", phrase: "Deep Dish Pizza" },
    { top: "Eggs", phrase: "Scrambled Eggs" },
    { top: "Burger", phrase: "Beef Burger" },
    { top: "Tacos", phrase: "Fish Tacos" },
    { top: "Wings", phrase: "Chicken Wings" },
    { top: "Potatoes", phrase: "Mashed Potatoes" },
    { top: "Bread", phrase: "Garlic Bread" },
    { top: "Salad", phrase: "Caesar Salad" },
    { top: "Rings", phrase: "Onion Rings" },
    { top: "Dog", phrase: "Corn Dog" },
    { top: "Jerky", phrase: "Beef Jerky" },
    { top: "Tea", phrase: "Iced Tea" },
    { top: "Chocolate", phrase: "Hot Chocolate" },
    { top: "Pizza", phrase: "Cheese Pizza" },
    { top: "Cobbler", phrase: "Peach Cobbler" },
    { top: "Pie", phrase: "Pumpkin Pie" },
    { top: "Nuggets", phrase: "Chicken Nuggets" }
  ],
  "Animals": [
    { top: "Bear", phrase: "Polar Bear" },
    { top: "Whale", phrase: "Killer Whale" },
    { top: "Fox", phrase: "Red Fox" },
    { top: "Leopard", phrase: "Snow Leopard" },
    { top: "Turtle", phrase: "Sea Turtle" },
    { top: "Panther", phrase: "Black Panther" },
    { top: "Shark", phrase: "Great White Shark" },
    { top: "Elephant", phrase: "Baby Elephant" },
    { top: "Boar", phrase: "Wild Boar" },
    { top: "Wolf", phrase: "Grey Wolf" },
    { top: "Crab", phrase: "Hermit Crab" },
    { top: "Bat", phrase: "Fruit Bat" },
    { top: "Bee", phrase: "Honey Bee" },
    { top: "Cobra", phrase: "King Cobra" },
    { top: "Goat", phrase: "Mountain Goat" },
    { top: "Panda", phrase: "Giant Panda" },
    { top: "Dragon", phrase: "Komodo Dragon" },
    { top: "Eel", phrase: "Electric Eel" },
    { top: "Squirrel", phrase: "Flying Squirrel" },
    { top: "Frog", phrase: "Poison Frog" },
    { top: "Owl", phrase: "Snowy Owl" },
    { top: "Penguin", phrase: "Emperor Penguin" },
    { top: "Jellyfish", phrase: "Moon Jellyfish" },
    { top: "Octopus", phrase: "Giant Octopus" },
    { top: "Lion", phrase: "Mountain Lion" },
    { top: "Tiger", phrase: "Bengal Tiger" },
    { top: "Rhino", phrase: "White Rhino" },
    { top: "Hippo", phrase: "Pygmy Hippo" },
    { top: "Gorilla", phrase: "Silverback Gorilla" },
    { top: "Chimpanzee", phrase: "Baby Chimpanzee" },
    { top: "Raccoon", phrase: "Masked Raccoon" },
    { top: "Skunk", phrase: "Striped Skunk" },
    { top: "Otter", phrase: "Sea Otter" },
    { top: "Peacock", phrase: "Blue Peacock" },
    { top: "Flamingo", phrase: "Pink Flamingo" }
  ],
  "Famous Folks": [
    { top: "Claus", phrase: "Santa Claus" },
    { top: "Einstein", phrase: "Albert Einstein" },
    { top: "Holmes", phrase: "Sherlock Holmes" },
    { top: "Lincoln", phrase: "Abraham Lincoln" },
    { top: "Jackson", phrase: "Michael Jackson" },
    { top: "Shakespeare", phrase: "William Shakespeare" },
    { top: "Washington", phrase: "George Washington" },
    { top: "Fairy", phrase: "The Tooth Fairy" },
    { top: "Vader", phrase: "Darth Vader" },
    { top: "America", phrase: "Captain America" },
    { top: "Sam", phrase: "Uncle Sam" },
    { top: "Lisa", phrase: "Mona Lisa" },
    { top: "Arthur", phrase: "King Arthur" },
    { top: "Hood", phrase: "Robin Hood" },
    { top: "Goose", phrase: "Mother Goose" },
    { top: "Lee", phrase: "Bruce Lee" },
    { top: "Disney", phrase: "Walt Disney" },
    { top: "Jobs", phrase: "Steve Jobs" },
    { top: "Musk", phrase: "Elon Musk" },
    { top: "Gates", phrase: "Bill Gates" },
    { top: "Curie", phrase: "Marie Curie" },
    { top: "Newton", phrase: "Isaac Newton" },
    { top: "Franklin", phrase: "Benjamin Franklin" },
    { top: "Mandela", phrase: "Nelson Mandela" },
    { top: "Freud", phrase: "Sigmund Freud" },
    { top: "Picasso", phrase: "Pablo Picasso" },
    { top: "Beethoven", phrase: "Ludwig Beethoven" },
    { top: "Mozart", phrase: "Wolfgang Mozart" },
    { top: "George", phrase: "Curious George" },
    { top: "Simpson", phrase: "Homer Simpson" },
    { top: "Poppins", phrase: "Mary Poppins" },
    { top: "Grimm", phrase: "Brothers Grimm" },
    { top: "Cleopatra", phrase: "Queen Cleopatra" },
    { top: "Caesar", phrase: "Julius Caesar" },
    { top: "King", phrase: "Martin Luther King" }
  ],
  "Everyday Things": [
    { top: "Clock", phrase: "Alarm Clock" },
    { top: "Brush", phrase: "Tooth Brush" },
    { top: "Cap", phrase: "Baseball Cap" },
    { top: "Cup", phrase: "Coffee Cup" },
    { top: "Bulb", phrase: "Light Bulb" },
    { top: "Bell", phrase: "Door Bell" },
    { top: "Truck", phrase: "Garbage Truck" },
    { top: "Phone", phrase: "Cell Phone" },
    { top: "Bottle", phrase: "Water Bottle" },
    { top: "Bag", phrase: "Sleeping Bag" },
    { top: "Pan", phrase: "Frying Pan" },
    { top: "Towel", phrase: "Paper Towel" },
    { top: "Light", phrase: "Traffic Light" },
    { top: "Cart", phrase: "Shopping Cart" },
    { top: "Fan", phrase: "Ceiling Fan" },
    { top: "Chain", phrase: "Key Chain" },
    { top: "Can", phrase: "Trash Can" },
    { top: "Watch", phrase: "Wrist Watch" },
    { top: "Lamp", phrase: "Desk Lamp" },
    { top: "Duck", phrase: "Rubber Duck" },
    { top: "Umbrella", phrase: "Beach Umbrella" },
    { top: "Mirror", phrase: "Bathroom Mirror" },
    { top: "Blanket", phrase: "Wool Blanket" },
    { top: "Pillow", phrase: "Feather Pillow" },
    { top: "Ladder", phrase: "Step Ladder" },
    { top: "Broom", phrase: "Push Broom" },
    { top: "Mop", phrase: "String Mop" },
    { top: "Scissors", phrase: "Kitchen Scissors" },
    { top: "Wallet", phrase: "Leather Wallet" },
    { top: "Backpack", phrase: "School Backpack" },
    { top: "Charger", phrase: "Phone Charger" },
    { top: "Remote", phrase: "TV Remote" },
    { top: "Toaster", phrase: "Pop Up Toaster" },
    { top: "Blender", phrase: "Kitchen Blender" },
    { top: "Mattress", phrase: "Air Mattress" }
  ],
  "Places": [
    { top: "Canyon", phrase: "Grand Canyon" },
    { top: "Pole", phrase: "North Pole" },
    { top: "City", phrase: "New York City" },
    { top: "Building", phrase: "Empire State Building" },
    { top: "Bridge", phrase: "Golden Gate Bridge" },
    { top: "Wall", phrase: "Great Wall of China" },
    { top: "Liberty", phrase: "Statue of Liberty" },
    { top: "Mountains", phrase: "Rocky Mountains" },
    { top: "Floor", phrase: "Ocean Floor" },
    { top: "Beach", phrase: "Sandy Beach" },
    { top: "Forest", phrase: "Dark Forest" },
    { top: "Theater", phrase: "Movie Theater" },
    { top: "Stop", phrase: "Bus Stop" },
    { top: "Yard", phrase: "Front Yard" },
    { top: "Station", phrase: "Fire Station" },
    { top: "Tower", phrase: "Eiffel Tower" },
    { top: "Square", phrase: "Times Square" },
    { top: "Falls", phrase: "Niagara Falls" },
    { top: "Desert", phrase: "Sahara Desert" },
    { top: "River", phrase: "Amazon River" },
    { top: "Volcano", phrase: "Active Volcano" },
    { top: "Island", phrase: "Tropical Island" },
    { top: "Cave", phrase: "Bat Cave" },
    { top: "Waterfall", phrase: "Hidden Waterfall" },
    { top: "Lagoon", phrase: "Blue Lagoon" },
    { top: "Reef", phrase: "Coral Reef" },
    { top: "Valley", phrase: "Silicon Valley" },
    { top: "Glacier", phrase: "Blue Glacier" },
    { top: "Prairie", phrase: "Open Prairie" },
    { top: "Swamp", phrase: "Dark Swamp" },
    { top: "Harbor", phrase: "Fishing Harbor" },
    { top: "Lighthouse", phrase: "Old Lighthouse" },
    { top: "Castle", phrase: "Stone Castle" },
    { top: "Palace", phrase: "Royal Palace" },
    { top: "Temple", phrase: "Ancient Temple" }
  ],
  "Actions & Sports": [
    { top: "Skating", phrase: "Ice Skating" },
    { top: "Climbing", phrase: "Rock Climbing" },
    { top: "Wrestling", phrase: "Arm Wrestling" },
    { top: "Rope", phrase: "Jump Rope" },
    { top: "Seek", phrase: "Hide and Seek" },
    { top: "War", phrase: "Tug of War" },
    { top: "Throw", phrase: "Free Throw" },
    { top: "Run", phrase: "Home Run" },
    { top: "Dunk", phrase: "Slam Dunk" },
    { top: "Jump", phrase: "High Jump" },
    { top: "Diving", phrase: "Deep Sea Diving" },
    { top: "Skating", phrase: "Speed Skating" },
    { top: "Wheel", phrase: "Cart Wheel" },
    { top: "Goose", phrase: "Duck Duck Goose" },
    { top: "Chairs", phrase: "Musical Chairs" },
    { top: "Race", phrase: "Sack Race" },
    { top: "Jump", phrase: "Long Jump" },
    { top: "Skating", phrase: "Figure Skating" },
    { top: "Tennis", phrase: "Table Tennis" },
    { top: "Tag", phrase: "Freeze Tag" },
    { top: "Boxing", phrase: "Kick Boxing" },
    { top: "Surfing", phrase: "Wind Surfing" },
    { top: "Skiing", phrase: "Water Skiing" },
    { top: "Bowling", phrase: "Ten Pin Bowling" },
    { top: "Archery", phrase: "Target Archery" },
    { top: "Fencing", phrase: "Sword Fencing" },
    { top: "Golfing", phrase: "Mini Golfing" },
    { top: "Juggling", phrase: "Ball Juggling" },
    { top: "Cycling", phrase: "Mountain Cycling" },
    { top: "Racing", phrase: "Horse Racing" },
    { top: "Diving", phrase: "Sky Diving" },
    { top: "Bungee", phrase: "Bungee Jumping" },
    { top: "Karate", phrase: "Karate Chop" },
    { top: "Yoga", phrase: "Power Yoga" },
    { top: "Sumo", phrase: "Sumo Wrestling" }
  ],
  "Random Fun": [
    { top: "Wand", phrase: "Magic Wand" },
    { top: "Machine", phrase: "Time Machine" },
    { top: "Coaster", phrase: "Roller Coaster" },
    { top: "Map", phrase: "Treasure Map" },
    { top: "Ship", phrase: "Space Ship" },
    { top: "Game", phrase: "Video Game" },
    { top: "Ship", phrase: "Pirate Ship" },
    { top: "Dragon", phrase: "Fire Breathing Dragon" },
    { top: "Moon", phrase: "Full Moon" },
    { top: "Star", phrase: "Shooting Star" },
    { top: "Sand", phrase: "Quick Sand" },
    { top: "Charm", phrase: "Lucky Charm" },
    { top: "Code", phrase: "Secret Code" },
    { top: "Arm", phrase: "Robot Arm" },
    { top: "Town", phrase: "Ghost Town" },
    { top: "Hero", phrase: "Super Hero" },
    { top: "Star", phrase: "Ninja Star" },
    { top: "Game", phrase: "Board Game" },
    { top: "Stick", phrase: "Glow Stick" },
    { top: "Wrap", phrase: "Bubble Wrap" },
    { top: "Castle", phrase: "Sand Castle" },
    { top: "Fort", phrase: "Blanket Fort" },
    { top: "Puzzle", phrase: "Jigsaw Puzzle" },
    { top: "Balloon", phrase: "Water Balloon" },
    { top: "Kite", phrase: "Box Kite" },
    { top: "Slingshot", phrase: "Rubber Slingshot" },
    { top: "Marbles", phrase: "Glass Marbles" },
    { top: "Puppet", phrase: "Hand Puppet" },
    { top: "Mask", phrase: "Superhero Mask" },
    { top: "Cape", phrase: "Super Cape" },
    { top: "Costume", phrase: "Halloween Costume" },
    { top: "Riddle", phrase: "Tricky Riddle" },
    { top: "Trick", phrase: "Magic Trick" },
    { top: "Spell", phrase: "Magic Spell" },
    { top: "Potion", phrase: "Love Potion" }
  ],
  "Tagalog": [
    { top: "Adobo", phrase: "Chicken Adobo" },
    { top: "Sinigang", phrase: "Pork Sinigang" },
    { top: "Halo", phrase: "Halo Halo" },
    { top: "Lumpia", phrase: "Lumpia Shanghai" },
    { top: "Bihon", phrase: "Pancit Bihon" },
    { top: "Flan", phrase: "Leche Flan" },
    { top: "Puto", phrase: "Puto Bumbong" },
    { top: "Sisig", phrase: "Sisig Baboy" },
    { top: "Kubo", phrase: "Bahay Kubo" },
    { top: "Jeepney", phrase: "Jeepney Ride" },
    { top: "Kumusta", phrase: "Kumusta Ka" },
    { top: "Mahal", phrase: "Mahal Kita" },
    { top: "Bahala", phrase: "Bahala Na" },
    { top: "Pacquiao", phrase: "Manny Pacquiao" },
    { top: "Boracay", phrase: "Boracay Beach" },
    { top: "Balut", phrase: "Duck Balut" },
    { top: "Tricycle", phrase: "Tricycle Driver" },
    { top: "Barangay", phrase: "Barangay Captain" }
  ]
};
