// Poetry for Neanderthals — the deck.
// Each card has a short "top" word worth +1, contained inside the full
// "phrase" worth +3. The challenge: describe both using only one-syllable
// clue words.
const DECK = {
  "Movies & Shows": [
    { top: "Wars", phrase: "Star Wars" },
    { top: "Park", phrase: "Jurassic Park" },
    { top: "King", phrase: "The Lion King" },
    { top: "Alone", phrase: "Home Alone" },
    { top: "Story", phrase: "Toy Story" },
    { top: "Woman", phrase: "Wonder Woman" },
    { top: "Nemo", phrase: "Finding Nemo" },
    { top: "Potter", phrase: "Harry Potter" },
    { top: "Tank", phrase: "Shark Tank" },
    { top: "Tales", phrase: "Duck Tales" },
    { top: "Age", phrase: "Ice Age" },
    { top: "Willy", phrase: "Free Willy" },
    { top: "Man", phrase: "Spider Man" },
    { top: "Mission", phrase: "Mission Impossible" },
    { top: "Panda", phrase: "Kung Fu Panda" }
  ],
  "Food & Drink": [
    { top: "Cheese", phrase: "Grilled Cheese" },
    { top: "Dog", phrase: "Hot Dog" },
    { top: "Fries", phrase: "French Fries" },
    { top: "Cream", phrase: "Ice Cream" },
    { top: "Butter", phrase: "Peanut Butter" },
    { top: "Pie", phrase: "Apple Pie" },
    { top: "Beer", phrase: "Root Beer" },
    { top: "Cake", phrase: "Birthday Cake" },
    { top: "Candy", phrase: "Cotton Candy" },
    { top: "Rice", phrase: "Fried Rice" },
    { top: "Bread", phrase: "Banana Bread" },
    { top: "Juice", phrase: "Orange Juice" },
    { top: "Chips", phrase: "Potato Chips" },
    { top: "Soup", phrase: "Chicken Soup" },
    { top: "Milk", phrase: "Chocolate Milk" }
  ],
  "Animals": [
    { top: "Bear", phrase: "Polar Bear" },
    { top: "Whale", phrase: "Killer Whale" },
    { top: "Fox", phrase: "Red Fox" },
    { top: "Leopard", phrase: "Snow Leopard" },
    { top: "Turtle", phrase: "Sea Turtle" },
    { top: "Panther", phrase: "Black Panther" },
    { top: "Shark", phrase: "Great White Shark" },
    { top: "Elephant", phrase: "Baby Elephant" },
    { top: "Boar", phrase: "Wild Boar" },
    { top: "Wolf", phrase: "Grey Wolf" },
    { top: "Crab", phrase: "Hermit Crab" },
    { top: "Bat", phrase: "Fruit Bat" },
    { top: "Bee", phrase: "Honey Bee" },
    { top: "Cobra", phrase: "King Cobra" },
    { top: "Goat", phrase: "Mountain Goat" }
  ],
  "Famous Folks": [
    { top: "Claus", phrase: "Santa Claus" },
    { top: "Einstein", phrase: "Albert Einstein" },
    { top: "Holmes", phrase: "Sherlock Holmes" },
    { top: "Lincoln", phrase: "Abraham Lincoln" },
    { top: "Jackson", phrase: "Michael Jackson" },
    { top: "Shakespeare", phrase: "William Shakespeare" },
    { top: "Washington", phrase: "George Washington" },
    { top: "Fairy", phrase: "The Tooth Fairy" },
    { top: "Vader", phrase: "Darth Vader" },
    { top: "America", phrase: "Captain America" },
    { top: "Sam", phrase: "Uncle Sam" },
    { top: "Lisa", phrase: "Mona Lisa" },
    { top: "Arthur", phrase: "King Arthur" },
    { top: "Hood", phrase: "Robin Hood" },
    { top: "Goose", phrase: "Mother Goose" }
  ],
  "Everyday Things": [
    { top: "Clock", phrase: "Alarm Clock" },
    { top: "Brush", phrase: "Tooth Brush" },
    { top: "Cap", phrase: "Baseball Cap" },
    { top: "Cup", phrase: "Coffee Cup" },
    { top: "Bulb", phrase: "Light Bulb" },
    { top: "Bell", phrase: "Door Bell" },
    { top: "Truck", phrase: "Garbage Truck" },
    { top: "Phone", phrase: "Cell Phone" },
    { top: "Bottle", phrase: "Water Bottle" },
    { top: "Bag", phrase: "Sleeping Bag" },
    { top: "Pan", phrase: "Frying Pan" },
    { top: "Towel", phrase: "Paper Towel" },
    { top: "Light", phrase: "Traffic Light" },
    { top: "Cart", phrase: "Shopping Cart" },
    { top: "Fan", phrase: "Ceiling Fan" }
  ],
  "Places": [
    { top: "Canyon", phrase: "Grand Canyon" },
    { top: "Pole", phrase: "North Pole" },
    { top: "City", phrase: "New York City" },
    { top: "Building", phrase: "Empire State Building" },
    { top: "Bridge", phrase: "Golden Gate Bridge" },
    { top: "Wall", phrase: "Great Wall of China" },
    { top: "Liberty", phrase: "Statue of Liberty" },
    { top: "Mountains", phrase: "Rocky Mountains" },
    { top: "Floor", phrase: "Ocean Floor" },
    { top: "Beach", phrase: "Sandy Beach" },
    { top: "Forest", phrase: "Dark Forest" },
    { top: "Theater", phrase: "Movie Theater" },
    { top: "Stop", phrase: "Bus Stop" },
    { top: "Yard", phrase: "Front Yard" },
    { top: "Station", phrase: "Fire Station" }
  ],
  "Actions & Sports": [
    { top: "Skating", phrase: "Ice Skating" },
    { top: "Climbing", phrase: "Rock Climbing" },
    { top: "Wrestling", phrase: "Arm Wrestling" },
    { top: "Rope", phrase: "Jump Rope" },
    { top: "Seek", phrase: "Hide and Seek" },
    { top: "War", phrase: "Tug of War" },
    { top: "Throw", phrase: "Free Throw" },
    { top: "Run", phrase: "Home Run" },
    { top: "Dunk", phrase: "Slam Dunk" },
    { top: "Jump", phrase: "High Jump" },
    { top: "Diving", phrase: "Deep Sea Diving" },
    { top: "Skating", phrase: "Speed Skating" },
    { top: "Wheel", phrase: "Cart Wheel" },
    { top: "Goose", phrase: "Duck Duck Goose" },
    { top: "Chairs", phrase: "Musical Chairs" }
  ],
  "Random Fun": [
    { top: "Wand", phrase: "Magic Wand" },
    { top: "Machine", phrase: "Time Machine" },
    { top: "Coaster", phrase: "Roller Coaster" },
    { top: "Map", phrase: "Treasure Map" },
    { top: "Ship", phrase: "Space Ship" },
    { top: "Game", phrase: "Video Game" },
    { top: "Ship", phrase: "Pirate Ship" },
    { top: "Dragon", phrase: "Fire Breathing Dragon" },
    { top: "Moon", phrase: "Full Moon" },
    { top: "Star", phrase: "Shooting Star" },
    { top: "Sand", phrase: "Quick Sand" },
    { top: "Charm", phrase: "Lucky Charm" },
    { top: "Code", phrase: "Secret Code" },
    { top: "Arm", phrase: "Robot Arm" },
    { top: "Town", phrase: "Ghost Town" }
  ]
};
