// Poetry for Neanderthals — the deck.
// Each card has a short "top" word worth +1, contained inside the full
// "phrase" worth +3. The challenge: describe both using only one-syllable
// clue words.
const DECK = {
  "Movies & Shows": [
    { top: "Wars", phrase: "Star Wars" },
    { top: "Park", phrase: "Jurassic Park" },
    { top: "King", phrase: "The Lion King" },
    { top: "Alone", phrase: "Home Alone" },
    { top: "Story", phrase: "Toy Story" },
    { top: "Woman", phrase: "Wonder Woman" },
    { top: "Nemo", phrase: "Finding Nemo" },
    { top: "Potter", phrase: "Harry Potter" },
    { top: "Tank", phrase: "Shark Tank" },
    { top: "Tales", phrase: "Duck Tales" },
    { top: "Age", phrase: "Ice Age" },
    { top: "Willy", phrase: "Free Willy" },
    { top: "Man", phrase: "Spider Man" },
    { top: "Mission", phrase: "Mission Impossible" },
    { top: "Panda", phrase: "Kung Fu Panda" },
    { top: "Kid", phrase: "The Karate Kid" },
    { top: "Strange", phrase: "Doctor Strange" },
    { top: "University", phrase: "Monsters University" },
    { top: "Race", phrase: "The Amazing Race" },
    { top: "Idol", phrase: "American Idol" },
    { top: "Future", phrase: "Back to the Future" },
    { top: "Furious", phrase: "Fast and Furious" },
    { top: "Apes", phrase: "Planet of the Apes" },
    { top: "Dead", phrase: "The Walking Dead" },
    { top: "Bad", phrase: "Breaking Bad" },
    { top: "Thrones", phrase: "Game of Thrones" },
    { top: "Things", phrase: "Stranger Things" },
    { top: "Theory", phrase: "The Big Bang Theory" },
    { top: "Blinders", phrase: "Peaky Blinders" },
    { top: "Prince", phrase: "The Fresh Prince" },
    { top: "Beast", phrase: "Beauty and the Beast" },
    { top: "Mermaid", phrase: "The Little Mermaid" },
    { top: "Beauty", phrase: "Sleeping Beauty" },
    { top: "White", phrase: "Snow White" },
    { top: "Pan", phrase: "Peter Pan" },
    { top: "Begins", phrase: "Batman Begins" },
    { top: "Knight", phrase: "The Dark Knight" },
    { top: "Man", phrase: "Iron Man" },
    { top: "Marvel", phrase: "Captain Marvel" },
    { top: "Family", phrase: "Modern Family" },
    { top: "Guy", phrase: "Family Guy" },
    { top: "Anatomy", phrase: "Grey's Anatomy" },
    { top: "Mother", phrase: "How I Met Your Mother" },
    { top: "Lebowski", phrase: "The Big Lebowski" },
    { top: "Gump", phrase: "Forrest Gump" },
    { top: "Hunting", phrase: "Good Will Hunting" },
    { top: "Godfather", phrase: "The Godfather" },
    { top: "Fiction", phrase: "Pulp Fiction" },
    { top: "Club", phrase: "Fight Club" },
    { top: "Matrix", phrase: "The Matrix" },
    { top: "World", phrase: "Jurassic World" },
    { top: "Avengers", phrase: "The Avengers" },
    { top: "Galaxy", phrase: "Guardians of the Galaxy" },
    { top: "Incredibles", phrase: "The Incredibles" },
    { top: "Me", phrase: "Despicable Me" },
    { top: "Forever", phrase: "Shrek Forever After" },
    { top: "Boots", phrase: "Puss in Boots" },
    { top: "Ralph", phrase: "Wreck It Ralph" },
    { top: "Red", phrase: "Turning Red" },
    { top: "Hulk", phrase: "The Incredible Hulk" },
    { top: "Ragnarok", phrase: "Thor Ragnarok" },
    { top: "Widow", phrase: "Black Widow" },
    { top: "Ant", phrase: "Ant Man" },
    { top: "Who", phrase: "Doctor Who" },
    { top: "Dawn", phrase: "Breaking Dawn" },
    { top: "Saga", phrase: "Twilight Saga" },
    { top: "Games", phrase: "The Hunger Games" },
    { top: "Series", phrase: "Divergent Series" },
    { top: "Runner", phrase: "Maze Runner" },
    { top: "See", phrase: "Now You See Me" },
    { top: "Sense", phrase: "The Sixth Sense" },
    { top: "Clause", phrase: "The Santa Clause" },
    { top: "Vacation", phrase: "Family Vacation" },
    { top: "Dumber", phrase: "Dumb and Dumber" },
    { top: "Nights", phrase: "Talladega Nights" },
    { top: "Brothers", phrase: "Step Brothers" },
    { top: "Hangover", phrase: "The Hangover" },
    { top: "Up", phrase: "Knocked Up" },
    { top: "Express", phrase: "Pineapple Express" },
    { top: "Thunder", phrase: "Tropic Thunder" },
    { top: "Parents", phrase: "Meet the Parents" },
    { top: "Improvement", phrase: "Home Improvement" },
    { top: "House", phrase: "Full House" },
    { top: "Bell", phrase: "Saved by the Bell" },
    { top: "Boy", phrase: "Boy Meets World" },
    { top: "Show", phrase: "That 70s Show" },
    { top: "Years", phrase: "The Wonder Years" },
    { top: "Lightning", phrase: "Grease Lightning" },
    { top: "Gun", phrase: "Top Gun" },
    { top: "Max", phrase: "Mad Max" },
    { top: "Hard", phrase: "Die Hard" },
    { top: "Weapon", phrase: "Lethal Weapon" },
    { top: "Black", phrase: "Men in Black" },
    { top: "Independence", phrase: "Independence Day" },
    { top: "Impact", phrase: "Deep Impact" },
    { top: "War", phrase: "World War Z" },
    { top: "Legend", phrase: "I Am Legend" },
    { top: "Us", phrase: "The Last of Us" },
    { top: "Squid", phrase: "Squid Game" },
    { top: "Heist", phrase: "Money Heist" }
  ],
  "Food & Drink": [
    { top: "Cheese", phrase: "Grilled Cheese" },
    { top: "Dog", phrase: "Hot Dog" },
    { top: "Fries", phrase: "French Fries" },
    { top: "Cream", phrase: "Ice Cream" },
    { top: "Butter", phrase: "Peanut Butter" },
    { top: "Pie", phrase: "Apple Pie" },
    { top: "Beer", phrase: "Root Beer" },
    { top: "Cake", phrase: "Birthday Cake" },
    { top: "Candy", phrase: "Cotton Candy" },
    { top: "Rice", phrase: "Fried Rice" },
    { top: "Bread", phrase: "Banana Bread" },
    { top: "Juice", phrase: "Orange Juice" },
    { top: "Chips", phrase: "Potato Chips" },
    { top: "Soup", phrase: "Chicken Soup" },
    { top: "Milk", phrase: "Chocolate Milk" },
    { top: "Steak", phrase: "Grilled Steak" },
    { top: "Syrup", phrase: "Maple Syrup" },
    { top: "Donut", phrase: "Glazed Donut" },
    { top: "Pizza", phrase: "Deep Dish Pizza" },
    { top: "Eggs", phrase: "Scrambled Eggs" },
    { top: "Burger", phrase: "Beef Burger" },
    { top: "Tacos", phrase: "Fish Tacos" },
    { top: "Wings", phrase: "Chicken Wings" },
    { top: "Potatoes", phrase: "Mashed Potatoes" },
    { top: "Bread", phrase: "Garlic Bread" },
    { top: "Salad", phrase: "Caesar Salad" },
    { top: "Rings", phrase: "Onion Rings" },
    { top: "Dog", phrase: "Corn Dog" },
    { top: "Jerky", phrase: "Beef Jerky" },
    { top: "Tea", phrase: "Iced Tea" },
    { top: "Chocolate", phrase: "Hot Chocolate" },
    { top: "Pizza", phrase: "Cheese Pizza" },
    { top: "Cobbler", phrase: "Peach Cobbler" },
    { top: "Pie", phrase: "Pumpkin Pie" },
    { top: "Nuggets", phrase: "Chicken Nuggets" },
    { top: "Sandwich", phrase: "Club Sandwich" },
    { top: "Salmon", phrase: "Grilled Salmon" },
    { top: "Stew", phrase: "Beef Stew" },
    { top: "Chowder", phrase: "Clam Chowder" },
    { top: "Cocktail", phrase: "Shrimp Cocktail" },
    { top: "Curry", phrase: "Chicken Curry" },
    { top: "Stroganoff", phrase: "Beef Stroganoff" },
    { top: "Cheese", phrase: "Mac and Cheese" },
    { top: "Beans", phrase: "Baked Beans" },
    { top: "Deviled", phrase: "Deviled Eggs" },
    { top: "Salad", phrase: "Potato Salad" },
    { top: "Bread", phrase: "Corn Bread" },
    { top: "Rolls", phrase: "Dinner Rolls" },
    { top: "Sourdough", phrase: "Sourdough Bread" },
    { top: "Bagel", phrase: "Bagel and Cream Cheese" },
    { top: "Cone", phrase: "Waffle Cone" },
    { top: "Split", phrase: "Banana Split" },
    { top: "Shake", phrase: "Milk Shake" },
    { top: "Float", phrase: "Root Beer Float" },
    { top: "Smoothie", phrase: "Fruit Smoothie" },
    { top: "Energy", phrase: "Energy Drink" },
    { top: "Sparkling", phrase: "Sparkling Water" },
    { top: "Coconut", phrase: "Coconut Water" },
    { top: "Cocoa", phrase: "Hot Cocoa" },
    { top: "Coffee", phrase: "Iced Coffee" },
    { top: "Shot", phrase: "Espresso Shot" },
    { top: "Roll", phrase: "Cinnamon Roll" },
    { top: "Ham", phrase: "Glazed Ham" },
    { top: "Chicken", phrase: "Fried Chicken" },
    { top: "Wings", phrase: "Buffalo Wings" },
    { top: "Fries", phrase: "Sweet Potato Fries" },
    { top: "Nachos", phrase: "Loaded Nachos" },
    { top: "Fondue", phrase: "Cheese Fondue" },
    { top: "Kabob", phrase: "Beef Kabob" },
    { top: "Shrimp", phrase: "Grilled Shrimp" },
    { top: "Lobster", phrase: "Lobster Tail" },
    { top: "Cakes", phrase: "Crab Cakes" },
    { top: "Chips", phrase: "Fish and Chips" },
    { top: "Loaf", phrase: "Meat Loaf" },
    { top: "Chops", phrase: "Pork Chops" },
    { top: "Turkey", phrase: "Turkey Sandwich" },
    { top: "Burger", phrase: "Veggie Burger" },
    { top: "Strips", phrase: "Bacon Strips" },
    { top: "Waffle", phrase: "Belgian Waffle" },
    { top: "Toast", phrase: "French Toast" },
    { top: "Stack", phrase: "Pancake Stack" },
    { top: "Bacon", phrase: "Maple Bacon" },
    { top: "Toffee", phrase: "Butter Toffee" },
    { top: "Caramel", phrase: "Caramel Apple" },
    { top: "Cane", phrase: "Candy Cane" },
    { top: "Gummy", phrase: "Gummy Bears" },
    { top: "Cookie", phrase: "Chocolate Chip Cookie" },
    { top: "Raisin", phrase: "Oatmeal Raisin" },
    { top: "Cake", phrase: "Cheese Cake" },
    { top: "Velvet", phrase: "Red Velvet Cake" },
    { top: "Carrot", phrase: "Carrot Cake" },
    { top: "Sundae", phrase: "Ice Cream Sundae" },
    { top: "Yogurt", phrase: "Frozen Yogurt" },
    { top: "Cheese", phrase: "Nacho Cheese" },
    { top: "Sandwich", phrase: "Cheese Sandwich" },
    { top: "Potato", phrase: "Baked Potato" },
    { top: "Corn", phrase: "Sweet Corn" },
    { top: "Cheese", phrase: "Cream Cheese" },
    { top: "Brittle", phrase: "Peanut Brittle" },
    { top: "Pudding", phrase: "Rice Pudding" }
  ],
  "Animals": [
    { top: "Bear", phrase: "Polar Bear" },
    { top: "Whale", phrase: "Killer Whale" },
    { top: "Fox", phrase: "Red Fox" },
    { top: "Leopard", phrase: "Snow Leopard" },
    { top: "Turtle", phrase: "Sea Turtle" },
    { top: "Panther", phrase: "Black Panther" },
    { top: "Shark", phrase: "Great White Shark" },
    { top: "Elephant", phrase: "Baby Elephant" },
    { top: "Boar", phrase: "Wild Boar" },
    { top: "Wolf", phrase: "Grey Wolf" },
    { top: "Crab", phrase: "Hermit Crab" },
    { top: "Bat", phrase: "Fruit Bat" },
    { top: "Bee", phrase: "Honey Bee" },
    { top: "Cobra", phrase: "King Cobra" },
    { top: "Goat", phrase: "Mountain Goat" },
    { top: "Panda", phrase: "Giant Panda" },
    { top: "Dragon", phrase: "Komodo Dragon" },
    { top: "Eel", phrase: "Electric Eel" },
    { top: "Squirrel", phrase: "Flying Squirrel" },
    { top: "Frog", phrase: "Poison Frog" },
    { top: "Owl", phrase: "Snowy Owl" },
    { top: "Penguin", phrase: "Emperor Penguin" },
    { top: "Jellyfish", phrase: "Moon Jellyfish" },
    { top: "Octopus", phrase: "Giant Octopus" },
    { top: "Lion", phrase: "Mountain Lion" },
    { top: "Tiger", phrase: "Bengal Tiger" },
    { top: "Rhino", phrase: "White Rhino" },
    { top: "Hippo", phrase: "Pygmy Hippo" },
    { top: "Gorilla", phrase: "Silverback Gorilla" },
    { top: "Chimpanzee", phrase: "Baby Chimpanzee" },
    { top: "Raccoon", phrase: "Masked Raccoon" },
    { top: "Skunk", phrase: "Striped Skunk" },
    { top: "Otter", phrase: "Sea Otter" },
    { top: "Peacock", phrase: "Blue Peacock" },
    { top: "Flamingo", phrase: "Pink Flamingo" },
    { top: "Grizzly", phrase: "Grizzly Bear" },
    { top: "Bear", phrase: "Black Bear" },
    { top: "Bear", phrase: "Panda Bear" },
    { top: "Humpback", phrase: "Humpback Whale" },
    { top: "Whale", phrase: "Blue Whale" },
    { top: "Dane", phrase: "Great Dane" },
    { top: "Retriever", phrase: "Golden Retriever" },
    { top: "Shepherd", phrase: "German Shepherd" },
    { top: "Siamese", phrase: "Siamese Cat" },
    { top: "Persian", phrase: "Persian Cat" },
    { top: "Eagle", phrase: "Bald Eagle" },
    { top: "Falcon", phrase: "Peregrine Falcon" },
    { top: "Owl", phrase: "Great Horned Owl" },
    { top: "Turkey", phrase: "Wild Turkey" },
    { top: "Lion", phrase: "Sea Lion" },
    { top: "Seal", phrase: "Harbor Seal" },
    { top: "Seal", phrase: "Fur Seal" },
    { top: "Jay", phrase: "Blue Jay" },
    { top: "Cardinal", phrase: "Red Cardinal" },
    { top: "Woodpecker", phrase: "Downy Woodpecker" },
    { top: "Mantis", phrase: "Praying Mantis" },
    { top: "Butterfly", phrase: "Monarch Butterfly" },
    { top: "Beetle", phrase: "Dung Beetle" },
    { top: "Ant", phrase: "Fire Ant" },
    { top: "Spider", phrase: "Black Widow Spider" },
    { top: "Tarantula", phrase: "Hairy Tarantula" },
    { top: "Scorpion", phrase: "Desert Scorpion" },
    { top: "Hammerhead", phrase: "Hammerhead Shark" },
    { top: "Shark", phrase: "Tiger Shark" },
    { top: "Ray", phrase: "Manta Ray" },
    { top: "Horse", phrase: "Sea Horse" },
    { top: "Fish", phrase: "Clown Fish" },
    { top: "Tang", phrase: "Blue Tang" },
    { top: "Heron", phrase: "Great Blue Heron" },
    { top: "Egret", phrase: "Snowy Egret" },
    { top: "Fox", phrase: "Arctic Fox" },
    { top: "Fox", phrase: "Fennec Fox" },
    { top: "Wolf", phrase: "Timber Wolf" },
    { top: "Coyote", phrase: "Prairie Coyote" },
    { top: "Jackal", phrase: "Golden Jackal" },
    { top: "Hyena", phrase: "Spotted Hyena" },
    { top: "Cheetah", phrase: "Cheetah Cub" },
    { top: "Leopard", phrase: "Leopard Seal" },
    { top: "Ox", phrase: "Musk Ox" },
    { top: "Sheep", phrase: "Bighorn Sheep" },
    { top: "Ibex", phrase: "Alpine Ibex" },
    { top: "Reindeer", phrase: "Flying Reindeer" },
    { top: "Moose", phrase: "Bull Moose" },
    { top: "Elk", phrase: "Roosevelt Elk" },
    { top: "Bison", phrase: "American Bison" },
    { top: "Buffalo", phrase: "Water Buffalo" },
    { top: "Zebra", phrase: "Plains Zebra" },
    { top: "Giraffe", phrase: "Baby Giraffe" },
    { top: "Kangaroo", phrase: "Red Kangaroo" },
    { top: "Koala", phrase: "Koala Bear" },
    { top: "Wombat", phrase: "Common Wombat" },
    { top: "Platypus", phrase: "Duck Billed Platypus" },
    { top: "Devil", phrase: "Tasmanian Devil" },
    { top: "Meerkat", phrase: "Desert Meerkat" },
    { top: "Camel", phrase: "Bactrian Camel" },
    { top: "Llama", phrase: "Wooly Llama" },
    { top: "Wolf", phrase: "Arctic Wolf" },
    { top: "Panda", phrase: "Red Panda" },
    { top: "Otter", phrase: "River Otter" },
    { top: "Owl", phrase: "Snow Owl" }
  ],
  "Famous Folks": [
    { top: "Claus", phrase: "Santa Claus" },
    { top: "Einstein", phrase: "Albert Einstein" },
    { top: "Holmes", phrase: "Sherlock Holmes" },
    { top: "Lincoln", phrase: "Abraham Lincoln" },
    { top: "Jackson", phrase: "Michael Jackson" },
    { top: "Shakespeare", phrase: "William Shakespeare" },
    { top: "Washington", phrase: "George Washington" },
    { top: "Fairy", phrase: "The Tooth Fairy" },
    { top: "Vader", phrase: "Darth Vader" },
    { top: "America", phrase: "Captain America" },
    { top: "Sam", phrase: "Uncle Sam" },
    { top: "Lisa", phrase: "Mona Lisa" },
    { top: "Arthur", phrase: "King Arthur" },
    { top: "Hood", phrase: "Robin Hood" },
    { top: "Goose", phrase: "Mother Goose" },
    { top: "Lee", phrase: "Bruce Lee" },
    { top: "Disney", phrase: "Walt Disney" },
    { top: "Jobs", phrase: "Steve Jobs" },
    { top: "Musk", phrase: "Elon Musk" },
    { top: "Gates", phrase: "Bill Gates" },
    { top: "Curie", phrase: "Marie Curie" },
    { top: "Newton", phrase: "Isaac Newton" },
    { top: "Franklin", phrase: "Benjamin Franklin" },
    { top: "Mandela", phrase: "Nelson Mandela" },
    { top: "Freud", phrase: "Sigmund Freud" },
    { top: "Picasso", phrase: "Pablo Picasso" },
    { top: "Beethoven", phrase: "Ludwig Beethoven" },
    { top: "Mozart", phrase: "Wolfgang Mozart" },
    { top: "George", phrase: "Curious George" },
    { top: "Simpson", phrase: "Homer Simpson" },
    { top: "Poppins", phrase: "Mary Poppins" },
    { top: "Grimm", phrase: "Brothers Grimm" },
    { top: "Cleopatra", phrase: "Queen Cleopatra" },
    { top: "Caesar", phrase: "Julius Caesar" },
    { top: "King", phrase: "Martin Luther King" },
    { top: "Darwin", phrase: "Charles Darwin" },
    { top: "Galilei", phrase: "Galileo Galilei" },
    { top: "Vinci", phrase: "Leonardo da Vinci" },
    { top: "Gogh", phrase: "Vincent van Gogh" },
    { top: "Churchill", phrase: "Winston Churchill" },
    { top: "Bonaparte", phrase: "Napoleon Bonaparte" },
    { top: "Alexander", phrase: "Alexander the Great" },
    { top: "Khan", phrase: "Genghis Khan" },
    { top: "Columbus", phrase: "Christopher Columbus" },
    { top: "Earhart", phrase: "Amelia Earhart" },
    { top: "Armstrong", phrase: "Neil Armstrong" },
    { top: "Parks", phrase: "Rosa Parks" },
    { top: "Luther", phrase: "Martin Luther" },
    { top: "Gandhi", phrase: "Mahatma Gandhi" },
    { top: "Teresa", phrase: "Mother Teresa" },
    { top: "Francis", phrase: "Pope Francis" },
    { top: "Elizabeth", phrase: "Queen Elizabeth" },
    { top: "Henry", phrase: "King Henry" },
    { top: "Charming", phrase: "Prince Charming" },
    { top: "Diana", phrase: "Princess Diana" },
    { top: "William", phrase: "Prince William" },
    { top: "Obama", phrase: "Barack Obama" },
    { top: "Biden", phrase: "Joe Biden" },
    { top: "Trump", phrase: "Donald Trump" },
    { top: "Clooney", phrase: "George Clooney" },
    { top: "Hanks", phrase: "Tom Hanks" },
    { top: "Pitt", phrase: "Brad Pitt" },
    { top: "Smith", phrase: "Will Smith" },
    { top: "Chan", phrase: "Jackie Chan" },
    { top: "Wayne", phrase: "Bruce Wayne" },
    { top: "Kent", phrase: "Clark Kent" },
    { top: "Parker", phrase: "Peter Parker" },
    { top: "Stark", phrase: "Tony Stark" },
    { top: "Bond", phrase: "James Bond" },
    { top: "Jones", phrase: "Indiana Jones" },
    { top: "Skywalker", phrase: "Luke Skywalker" },
    { top: "Solo", phrase: "Han Solo" },
    { top: "Yoda", phrase: "Master Yoda" },
    { top: "Kenobi", phrase: "Obi Wan Kenobi" },
    { top: "Baggins", phrase: "Frodo Baggins" },
    { top: "Gandalf", phrase: "Gandalf the Grey" },
    { top: "Houdini", phrase: "Harry Houdini" },
    { top: "Tesla", phrase: "Nikola Tesla" },
    { top: "Edison", phrase: "Thomas Edison" },
    { top: "Bell", phrase: "Alexander Graham Bell" },
    { top: "Ford", phrase: "Henry Ford" },
    { top: "Whitman", phrase: "Walt Whitman" },
    { top: "Poe", phrase: "Edgar Allan Poe" },
    { top: "Twain", phrase: "Mark Twain" },
    { top: "King", phrase: "Stephen King" },
    { top: "Rowling", phrase: "J K Rowling" },
    { top: "Christie", phrase: "Agatha Christie" },
    { top: "Lee", phrase: "Stan Lee" },
    { top: "Winfrey", phrase: "Oprah Winfrey" },
    { top: "DeGeneres", phrase: "Ellen DeGeneres" },
    { top: "Johnson", phrase: "Dwayne Johnson" },
    { top: "Williams", phrase: "Serena Williams" },
    { top: "Jordan", phrase: "Michael Jordan" },
    { top: "Ruth", phrase: "Babe Ruth" },
    { top: "Ali", phrase: "Muhammad Ali" },
    { top: "Bolt", phrase: "Usain Bolt" },
    { top: "Ronaldo", phrase: "Cristiano Ronaldo" },
    { top: "Messi", phrase: "Lionel Messi" },
    { top: "Spielberg", phrase: "Steven Spielberg" },
    { top: "Cameron", phrase: "James Cameron" }
  ],
  "Everyday Things": [
    { top: "Clock", phrase: "Alarm Clock" },
    { top: "Brush", phrase: "Tooth Brush" },
    { top: "Cap", phrase: "Baseball Cap" },
    { top: "Cup", phrase: "Coffee Cup" },
    { top: "Bulb", phrase: "Light Bulb" },
    { top: "Bell", phrase: "Door Bell" },
    { top: "Truck", phrase: "Garbage Truck" },
    { top: "Phone", phrase: "Cell Phone" },
    { top: "Bottle", phrase: "Water Bottle" },
    { top: "Bag", phrase: "Sleeping Bag" },
    { top: "Pan", phrase: "Frying Pan" },
    { top: "Towel", phrase: "Paper Towel" },
    { top: "Light", phrase: "Traffic Light" },
    { top: "Cart", phrase: "Shopping Cart" },
    { top: "Fan", phrase: "Ceiling Fan" },
    { top: "Chain", phrase: "Key Chain" },
    { top: "Can", phrase: "Trash Can" },
    { top: "Watch", phrase: "Wrist Watch" },
    { top: "Lamp", phrase: "Desk Lamp" },
    { top: "Duck", phrase: "Rubber Duck" },
    { top: "Umbrella", phrase: "Beach Umbrella" },
    { top: "Mirror", phrase: "Bathroom Mirror" },
    { top: "Blanket", phrase: "Wool Blanket" },
    { top: "Pillow", phrase: "Feather Pillow" },
    { top: "Ladder", phrase: "Step Ladder" },
    { top: "Broom", phrase: "Push Broom" },
    { top: "Mop", phrase: "String Mop" },
    { top: "Scissors", phrase: "Kitchen Scissors" },
    { top: "Wallet", phrase: "Leather Wallet" },
    { top: "Backpack", phrase: "School Backpack" },
    { top: "Charger", phrase: "Phone Charger" },
    { top: "Remote", phrase: "TV Remote" },
    { top: "Toaster", phrase: "Pop Up Toaster" },
    { top: "Blender", phrase: "Kitchen Blender" },
    { top: "Mattress", phrase: "Air Mattress" },
    { top: "Hose", phrase: "Garden Hose" },
    { top: "Mower", phrase: "Lawn Mower" },
    { top: "Blower", phrase: "Leaf Blower" },
    { top: "Drill", phrase: "Power Drill" },
    { top: "Hammer", phrase: "Claw Hammer" },
    { top: "Driver", phrase: "Screw Driver" },
    { top: "Tape", phrase: "Duct Tape" },
    { top: "Glue", phrase: "Super Glue" },
    { top: "Note", phrase: "Sticky Note" },
    { top: "Clip", phrase: "Paper Clip" },
    { top: "Band", phrase: "Rubber Band" },
    { top: "Pin", phrase: "Safety Pin" },
    { top: "Pin", phrase: "Bobby Pin" },
    { top: "Dryer", phrase: "Hair Dryer" },
    { top: "Iron", phrase: "Curling Iron" },
    { top: "Razor", phrase: "Electric Razor" },
    { top: "Towel", phrase: "Bath Towel" },
    { top: "Curtain", phrase: "Shower Curtain" },
    { top: "Mat", phrase: "Bath Mat" },
    { top: "Paper", phrase: "Toilet Paper" },
    { top: "Bag", phrase: "Trash Bag" },
    { top: "Bin", phrase: "Garbage Bin" },
    { top: "Bin", phrase: "Recycling Bin" },
    { top: "Soap", phrase: "Dish Soap" },
    { top: "Sanitizer", phrase: "Hand Sanitizer" },
    { top: "Soap", phrase: "Bar Soap" },
    { top: "Paste", phrase: "Tooth Paste" },
    { top: "Floss", phrase: "Dental Floss" },
    { top: "Clipper", phrase: "Nail Clipper" },
    { top: "Robe", phrase: "Bath Robe" },
    { top: "Key", phrase: "House Key" },
    { top: "Knob", phrase: "Door Knob" },
    { top: "Blind", phrase: "Window Blind" },
    { top: "Light", phrase: "Ceiling Light" },
    { top: "Cord", phrase: "Extension Cord" },
    { top: "Strip", phrase: "Power Strip" },
    { top: "Outlet", phrase: "Wall Outlet" },
    { top: "Switch", phrase: "Light Switch" },
    { top: "Detector", phrase: "Smoke Detector" },
    { top: "Extinguisher", phrase: "Fire Extinguisher" },
    { top: "Kit", phrase: "First Aid Kit" },
    { top: "Aid", phrase: "Band Aid" },
    { top: "Pack", phrase: "Ice Pack" },
    { top: "Pad", phrase: "Heating Pad" },
    { top: "Mask", phrase: "Sleeping Mask" },
    { top: "Plugs", phrase: "Ear Plugs" },
    { top: "Glasses", phrase: "Reading Glasses" },
    { top: "Lens", phrase: "Contact Lens" },
    { top: "Stand", phrase: "Umbrella Stand" },
    { top: "Rack", phrase: "Coat Rack" },
    { top: "Rack", phrase: "Shoe Rack" },
    { top: "Mat", phrase: "Welcome Mat" },
    { top: "Mat", phrase: "Door Mat" },
    { top: "Box", phrase: "Mail Box" },
    { top: "Box", phrase: "Tissue Box" },
    { top: "Box", phrase: "Cardboard Box" },
    { top: "Tape", phrase: "Sticky Tape" },
    { top: "Clock", phrase: "Wall Clock" },
    { top: "Clock", phrase: "Cuckoo Clock" },
    { top: "Fan", phrase: "Table Fan" },
    { top: "Lamp", phrase: "Floor Lamp" },
    { top: "Light", phrase: "Night Light" },
    { top: "Ladder", phrase: "Extension Ladder" },
    { top: "Stool", phrase: "Step Stool" },
    { top: "Needle", phrase: "Sewing Needle" }
  ],
  "Places": [
    { top: "Canyon", phrase: "Grand Canyon" },
    { top: "Pole", phrase: "North Pole" },
    { top: "City", phrase: "New York City" },
    { top: "Building", phrase: "Empire State Building" },
    { top: "Bridge", phrase: "Golden Gate Bridge" },
    { top: "Wall", phrase: "Great Wall of China" },
    { top: "Liberty", phrase: "Statue of Liberty" },
    { top: "Mountains", phrase: "Rocky Mountains" },
    { top: "Floor", phrase: "Ocean Floor" },
    { top: "Beach", phrase: "Sandy Beach" },
    { top: "Forest", phrase: "Dark Forest" },
    { top: "Theater", phrase: "Movie Theater" },
    { top: "Stop", phrase: "Bus Stop" },
    { top: "Yard", phrase: "Front Yard" },
    { top: "Station", phrase: "Fire Station" },
    { top: "Tower", phrase: "Eiffel Tower" },
    { top: "Square", phrase: "Times Square" },
    { top: "Falls", phrase: "Niagara Falls" },
    { top: "Desert", phrase: "Sahara Desert" },
    { top: "River", phrase: "Amazon River" },
    { top: "Volcano", phrase: "Active Volcano" },
    { top: "Island", phrase: "Tropical Island" },
    { top: "Cave", phrase: "Bat Cave" },
    { top: "Waterfall", phrase: "Hidden Waterfall" },
    { top: "Lagoon", phrase: "Blue Lagoon" },
    { top: "Reef", phrase: "Coral Reef" },
    { top: "Valley", phrase: "Silicon Valley" },
    { top: "Glacier", phrase: "Blue Glacier" },
    { top: "Prairie", phrase: "Open Prairie" },
    { top: "Swamp", phrase: "Dark Swamp" },
    { top: "Harbor", phrase: "Fishing Harbor" },
    { top: "Lighthouse", phrase: "Old Lighthouse" },
    { top: "Castle", phrase: "Stone Castle" },
    { top: "Palace", phrase: "Royal Palace" },
    { top: "Temple", phrase: "Ancient Temple" },
    { top: "Everest", phrase: "Mount Everest" },
    { top: "Fuji", phrase: "Mount Fuji" },
    { top: "Rushmore", phrase: "Mount Rushmore" },
    { top: "Central", phrase: "Grand Central Station" },
    { top: "Park", phrase: "Central Park" },
    { top: "Park", phrase: "Hyde Park" },
    { top: "Buckingham", phrase: "Buckingham Palace" },
    { top: "House", phrase: "White House" },
    { top: "Barrier", phrase: "Great Barrier Reef" },
    { top: "Sea", phrase: "Dead Sea" },
    { top: "Sea", phrase: "Red Sea" },
    { top: "Sea", phrase: "Caribbean Sea" },
    { top: "Pacific", phrase: "Pacific Ocean" },
    { top: "Atlantic", phrase: "Atlantic Ocean" },
    { top: "Circle", phrase: "Arctic Circle" },
    { top: "Shelf", phrase: "Antarctic Ice Shelf" },
    { top: "Yellowstone", phrase: "Yellowstone Park" },
    { top: "Teton", phrase: "Grand Teton" },
    { top: "Valley", phrase: "Death Valley" },
    { top: "Valley", phrase: "Monument Valley" },
    { top: "Strip", phrase: "Las Vegas Strip" },
    { top: "Boulevard", phrase: "Sunset Boulevard" },
    { top: "Street", phrase: "Wall Street" },
    { top: "Street", phrase: "Main Street" },
    { top: "Broadway", phrase: "Broadway Theater" },
    { top: "Sign", phrase: "Hollywood Sign" },
    { top: "Hills", phrase: "Beverly Hills" },
    { top: "Air", phrase: "Bel Air" },
    { top: "Italy", phrase: "Little Italy" },
    { top: "Quarter", phrase: "French Quarter" },
    { top: "Square", phrase: "Red Square" },
    { top: "Square", phrase: "Tiananmen Square" },
    { top: "Opera", phrase: "Sydney Opera House" },
    { top: "Ben", phrase: "Big Ben" },
    { top: "Bridge", phrase: "London Bridge" },
    { top: "Bridge", phrase: "Tower Bridge" },
    { top: "Tower", phrase: "Leaning Tower" },
    { top: "Needle", phrase: "Space Needle" },
    { top: "Beach", phrase: "Silicon Beach" },
    { top: "Beach", phrase: "Venice Beach" },
    { top: "Beach", phrase: "Bondi Beach" },
    { top: "Coast", phrase: "Ivory Coast" },
    { top: "Coast", phrase: "Gold Coast" },
    { top: "Coast", phrase: "West Coast" },
    { top: "Rainforest", phrase: "Amazon Rainforest" },
    { top: "Forest", phrase: "Black Forest" },
    { top: "Forest", phrase: "Enchanted Forest" },
    { top: "Park", phrase: "National Park" },
    { top: "Garden", phrase: "Botanical Garden" },
    { top: "Garden", phrase: "Secret Garden" },
    { top: "Garden", phrase: "Rose Garden" },
    { top: "Garden", phrase: "Zen Garden" },
    { top: "Market", phrase: "Farmers Market" },
    { top: "Market", phrase: "Fish Market" },
    { top: "Market", phrase: "Night Market" },
    { top: "Market", phrase: "Flea Market" },
    { top: "Mall", phrase: "Shopping Mall" },
    { top: "Court", phrase: "Food Court" },
    { top: "Court", phrase: "Tennis Court" },
    { top: "Court", phrase: "Basketball Court" },
    { top: "Square", phrase: "Town Square" },
    { top: "Hall", phrase: "City Hall" },
    { top: "Hall", phrase: "Concert Hall" },
    { top: "Hotel", phrase: "Grand Hotel" },
    { top: "Strip", phrase: "Sunset Strip" }
  ],
  "Actions & Sports": [
    { top: "Skating", phrase: "Ice Skating" },
    { top: "Climbing", phrase: "Rock Climbing" },
    { top: "Wrestling", phrase: "Arm Wrestling" },
    { top: "Rope", phrase: "Jump Rope" },
    { top: "Seek", phrase: "Hide and Seek" },
    { top: "War", phrase: "Tug of War" },
    { top: "Throw", phrase: "Free Throw" },
    { top: "Run", phrase: "Home Run" },
    { top: "Dunk", phrase: "Slam Dunk" },
    { top: "Jump", phrase: "High Jump" },
    { top: "Diving", phrase: "Deep Sea Diving" },
    { top: "Skating", phrase: "Speed Skating" },
    { top: "Wheel", phrase: "Cart Wheel" },
    { top: "Goose", phrase: "Duck Duck Goose" },
    { top: "Chairs", phrase: "Musical Chairs" },
    { top: "Race", phrase: "Sack Race" },
    { top: "Jump", phrase: "Long Jump" },
    { top: "Skating", phrase: "Figure Skating" },
    { top: "Tennis", phrase: "Table Tennis" },
    { top: "Tag", phrase: "Freeze Tag" },
    { top: "Boxing", phrase: "Kick Boxing" },
    { top: "Surfing", phrase: "Wind Surfing" },
    { top: "Skiing", phrase: "Water Skiing" },
    { top: "Bowling", phrase: "Ten Pin Bowling" },
    { top: "Archery", phrase: "Target Archery" },
    { top: "Fencing", phrase: "Sword Fencing" },
    { top: "Golfing", phrase: "Mini Golfing" },
    { top: "Juggling", phrase: "Ball Juggling" },
    { top: "Cycling", phrase: "Mountain Cycling" },
    { top: "Racing", phrase: "Horse Racing" },
    { top: "Diving", phrase: "Sky Diving" },
    { top: "Bungee", phrase: "Bungee Jumping" },
    { top: "Karate", phrase: "Karate Chop" },
    { top: "Yoga", phrase: "Power Yoga" },
    { top: "Sumo", phrase: "Sumo Wrestling" },
    { top: "Bat", phrase: "Baseball Bat" },
    { top: "Glove", phrase: "Baseball Glove" },
    { top: "Ball", phrase: "Soccer Ball" },
    { top: "Hoop", phrase: "Basketball Hoop" },
    { top: "Helmet", phrase: "Football Helmet" },
    { top: "Stick", phrase: "Hockey Stick" },
    { top: "Hockey", phrase: "Ice Hockey" },
    { top: "Hockey", phrase: "Field Hockey" },
    { top: "Spike", phrase: "Volleyball Spike" },
    { top: "Volleyball", phrase: "Beach Volleyball" },
    { top: "Tackle", phrase: "Rugby Tackle" },
    { top: "Bat", phrase: "Cricket Bat" },
    { top: "Racket", phrase: "Badminton Racket" },
    { top: "Court", phrase: "Squash Court" },
    { top: "Pong", phrase: "Ping Pong" },
    { top: "Ball", phrase: "Kick Ball" },
    { top: "Race", phrase: "Relay Race" },
    { top: "Marathon", phrase: "Marathon Run" },
    { top: "Hurdle", phrase: "Hurdle Race" },
    { top: "Vault", phrase: "Pole Vault" },
    { top: "Put", phrase: "Shot Put" },
    { top: "Javelin", phrase: "Javelin Throw" },
    { top: "Discus", phrase: "Discus Throw" },
    { top: "Triple", phrase: "Triple Jump" },
    { top: "Country", phrase: "Cross Country" },
    { top: "Trail", phrase: "Trail Running" },
    { top: "Bouldering", phrase: "Rock Bouldering" },
    { top: "Climbing", phrase: "Free Climbing" },
    { top: "Climbing", phrase: "Ice Climbing" },
    { top: "Boarding", phrase: "Snow Boarding" },
    { top: "Boarding", phrase: "Skate Boarding" },
    { top: "Boarding", phrase: "Wake Boarding" },
    { top: "Boarding", phrase: "Paddle Boarding" },
    { top: "Rafting", phrase: "White Water Rafting" },
    { top: "Kayak", phrase: "Kayak Racing" },
    { top: "Canoe", phrase: "Canoe Racing" },
    { top: "Rowing", phrase: "Rowing Team" },
    { top: "Lifting", phrase: "Weight Lifting" },
    { top: "Lifting", phrase: "Power Lifting" },
    { top: "Curl", phrase: "Arm Curl" },
    { top: "Up", phrase: "Push Up" },
    { top: "Up", phrase: "Pull Up" },
    { top: "Up", phrase: "Sit Up" },
    { top: "Jack", phrase: "Jumping Jack" },
    { top: "Squat", phrase: "Jump Squat" },
    { top: "Lunge", phrase: "Lunge Walk" },
    { top: "Chi", phrase: "Tai Chi" },
    { top: "Flip", phrase: "Kick Flip" },
    { top: "Flip", phrase: "Back Flip" },
    { top: "Flip", phrase: "Front Flip" },
    { top: "Spring", phrase: "Hand Spring" },
    { top: "Somersault", phrase: "Forward Somersault" },
    { top: "Beam", phrase: "Balance Beam" },
    { top: "Bars", phrase: "Uneven Bars" },
    { top: "Horse", phrase: "Pommel Horse" },
    { top: "Rhythmic", phrase: "Rhythmic Gymnastics" },
    { top: "Synchronized", phrase: "Synchronized Swimming" },
    { top: "Freestyle", phrase: "Freestyle Swimming" },
    { top: "Backstroke", phrase: "Backstroke Swim" },
    { top: "Stroke", phrase: "Butterfly Stroke" },
    { top: "Stroke", phrase: "Breast Stroke" },
    { top: "Board", phrase: "Diving Board" },
    { top: "Polo", phrase: "Water Polo" },
    { top: "Drive", phrase: "Long Drive" },
    { top: "Shot", phrase: "Slap Shot" }
  ],
  "Random Fun": [
    { top: "Wand", phrase: "Magic Wand" },
    { top: "Machine", phrase: "Time Machine" },
    { top: "Coaster", phrase: "Roller Coaster" },
    { top: "Map", phrase: "Treasure Map" },
    { top: "Ship", phrase: "Space Ship" },
    { top: "Game", phrase: "Video Game" },
    { top: "Ship", phrase: "Pirate Ship" },
    { top: "Dragon", phrase: "Fire Breathing Dragon" },
    { top: "Moon", phrase: "Full Moon" },
    { top: "Star", phrase: "Shooting Star" },
    { top: "Sand", phrase: "Quick Sand" },
    { top: "Charm", phrase: "Lucky Charm" },
    { top: "Code", phrase: "Secret Code" },
    { top: "Arm", phrase: "Robot Arm" },
    { top: "Town", phrase: "Ghost Town" },
    { top: "Hero", phrase: "Super Hero" },
    { top: "Star", phrase: "Ninja Star" },
    { top: "Game", phrase: "Board Game" },
    { top: "Stick", phrase: "Glow Stick" },
    { top: "Wrap", phrase: "Bubble Wrap" },
    { top: "Castle", phrase: "Sand Castle" },
    { top: "Fort", phrase: "Blanket Fort" },
    { top: "Puzzle", phrase: "Jigsaw Puzzle" },
    { top: "Balloon", phrase: "Water Balloon" },
    { top: "Kite", phrase: "Box Kite" },
    { top: "Slingshot", phrase: "Rubber Slingshot" },
    { top: "Marbles", phrase: "Glass Marbles" },
    { top: "Puppet", phrase: "Hand Puppet" },
    { top: "Mask", phrase: "Superhero Mask" },
    { top: "Cape", phrase: "Super Cape" },
    { top: "Costume", phrase: "Halloween Costume" },
    { top: "Riddle", phrase: "Tricky Riddle" },
    { top: "Trick", phrase: "Magic Trick" },
    { top: "Spell", phrase: "Magic Spell" },
    { top: "Potion", phrase: "Love Potion" },
    { top: "Hat", phrase: "Wizard Hat" },
    { top: "Broom", phrase: "Witch Broom" },
    { top: "Carpet", phrase: "Magic Carpet" },
    { top: "Ball", phrase: "Crystal Ball" },
    { top: "Teller", phrase: "Fortune Teller" },
    { top: "Card", phrase: "Tarot Card" },
    { top: "Well", phrase: "Wishing Well" },
    { top: "Lamp", phrase: "Genie Lamp" },
    { top: "Carpet", phrase: "Flying Carpet" },
    { top: "Cloak", phrase: "Invisible Cloak" },
    { top: "Mirror", phrase: "Magic Mirror" },
    { top: "Sword", phrase: "Enchanted Sword" },
    { top: "Key", phrase: "Golden Key" },
    { top: "Door", phrase: "Secret Door" },
    { top: "Treasure", phrase: "Hidden Treasure" },
    { top: "Flag", phrase: "Pirate Flag" },
    { top: "Skull", phrase: "Skull and Crossbones" },
    { top: "Gold", phrase: "Buried Gold" },
    { top: "Chest", phrase: "Treasure Chest" },
    { top: "Bottle", phrase: "Message in a Bottle" },
    { top: "Airplane", phrase: "Paper Airplane" },
    { top: "Soldier", phrase: "Toy Soldier" },
    { top: "Chicken", phrase: "Rubber Chicken" },
    { top: "Cushion", phrase: "Whoopee Cushion" },
    { top: "Mustache", phrase: "Fake Mustache" },
    { top: "Nose", phrase: "Clown Nose" },
    { top: "Hat", phrase: "Party Hat" },
    { top: "Cannon", phrase: "Confetti Cannon" },
    { top: "String", phrase: "Silly String" },
    { top: "Gun", phrase: "Water Gun" },
    { top: "Gun", phrase: "Squirt Gun" },
    { top: "Dart", phrase: "Nerf Dart" },
    { top: "Slime", phrase: "Slime Ball" },
    { top: "Putty", phrase: "Silly Putty" },
    { top: "Eight", phrase: "Magic Eight Ball" },
    { top: "Cube", phrase: "Rubik's Cube" },
    { top: "Box", phrase: "Puzzle Box" },
    { top: "Question", phrase: "Trick Question" },
    { top: "Teaser", phrase: "Brain Teaser" },
    { top: "Search", phrase: "Word Search" },
    { top: "Crossword", phrase: "Crossword Puzzle" },
    { top: "Scavenger", phrase: "Scavenger Hunt" },
    { top: "Hunt", phrase: "Treasure Hunt" },
    { top: "Hunt", phrase: "Egg Hunt" },
    { top: "Pinata", phrase: "Pinata Candy" },
    { top: "Balloon", phrase: "Birthday Balloon" },
    { top: "Popper", phrase: "Party Popper" },
    { top: "Streamers", phrase: "Paper Streamers" },
    { top: "Ball", phrase: "Disco Ball" },
    { top: "Lamp", phrase: "Lava Lamp" },
    { top: "Chair", phrase: "Bean Bag Chair" },
    { top: "Chair", phrase: "Rocking Chair" },
    { top: "Trampoline", phrase: "Trampoline Jump" },
    { top: "Stick", phrase: "Pogo Stick" },
    { top: "Hoop", phrase: "Hula Hoop" },
    { top: "Fan", phrase: "Paper Fan" },
    { top: "Slide", phrase: "Water Slide" },
    { top: "Round", phrase: "Merry Go Round" },
    { top: "Wheel", phrase: "Ferris Wheel" },
    { top: "Cars", phrase: "Bumper Cars" },
    { top: "Candy", phrase: "Candy Apple" },
    { top: "Gum", phrase: "Bubble Gum" },
    { top: "Gum", phrase: "Chewing Gum" },
    { top: "Face", phrase: "Silly Face" },
    { top: "Kazoo", phrase: "Kazoo Toy" }
  ],
  "Tagalog": [
    { top: "Adobo", phrase: "Chicken Adobo" },
    { top: "Sinigang", phrase: "Pork Sinigang" },
    { top: "Halo", phrase: "Halo Halo" },
    { top: "Lumpia", phrase: "Lumpia Shanghai" },
    { top: "Bihon", phrase: "Pancit Bihon" },
    { top: "Flan", phrase: "Leche Flan" },
    { top: "Puto", phrase: "Puto Bumbong" },
    { top: "Sisig", phrase: "Sisig Baboy" },
    { top: "Kubo", phrase: "Bahay Kubo" },
    { top: "Jeepney", phrase: "Jeepney Ride" },
    { top: "Kumusta", phrase: "Kumusta Ka" },
    { top: "Mahal", phrase: "Mahal Kita" },
    { top: "Bahala", phrase: "Bahala Na" },
    { top: "Pacquiao", phrase: "Manny Pacquiao" },
    { top: "Boracay", phrase: "Boracay Beach" },
    { top: "Balut", phrase: "Duck Balut" },
    { top: "Tricycle", phrase: "Tricycle Driver" },
    { top: "Barangay", phrase: "Barangay Captain" },
    { top: "Kaldereta", phrase: "Beef Kaldereta" },
    { top: "Kaldereta", phrase: "Pork Kaldereta" },
    { top: "Tinola", phrase: "Chicken Tinola" },
    { top: "Bicol", phrase: "Bicol Express" },
    { top: "Laing", phrase: "Laing Gata" },
    { top: "Dinuguan", phrase: "Dinuguan Stew" },
    { top: "Dinuguan", phrase: "Pork Dinuguan" },
    { top: "Inasal", phrase: "Chicken Inasal" },
    { top: "Lechon", phrase: "Lechon Baboy" },
    { top: "Pata", phrase: "Crispy Pata" },
    { top: "Bulalo", phrase: "Bulalo Soup" },
    { top: "Bulalo", phrase: "Beef Bulalo" },
    { top: "Tapsilog", phrase: "Tapsilog Breakfast" },
    { top: "Longganisa", phrase: "Longganisa Sausage" },
    { top: "Tocino", phrase: "Tocino Breakfast" },
    { top: "Champorado", phrase: "Champorado Rice" },
    { top: "Caldo", phrase: "Arroz Caldo" },
    { top: "Goto", phrase: "Goto Rice" },
    { top: "Palabok", phrase: "Pancit Palabok" },
    { top: "Malabon", phrase: "Pancit Malabon" },
    { top: "Afritada", phrase: "Chicken Afritada" },
    { top: "Afritada", phrase: "Pork Afritada" },
    { top: "Mechado", phrase: "Beef Mechado" },
    { top: "Kare", phrase: "Kare Kare" },
    { top: "Pinakbet", phrase: "Pinakbet Vegetable" },
    { top: "Bagoong", phrase: "Bagoong Rice" },
    { top: "Sinigang", phrase: "Sinigang Baboy" },
    { top: "Sinigang", phrase: "Sinigang Baka" },
    { top: "Turon", phrase: "Turon Saging" },
    { top: "Turon", phrase: "Banana Turon" },
    { top: "Buko", phrase: "Buko Pie" },
    { top: "Buko", phrase: "Buko Juice" },
    { top: "Halaya", phrase: "Halaya Ube" },
    { top: "Halaya", phrase: "Ube Halaya" },
    { top: "Polvoron", phrase: "Polvoron Candy" },
    { top: "Pastillas", phrase: "Pastillas Candy" },
    { top: "Suman", phrase: "Suman Rice Cake" },
    { top: "Bibingka", phrase: "Bibingka Rice Cake" },
    { top: "Kutsinta", phrase: "Kutsinta Rice Cake" },
    { top: "Taho", phrase: "Taho Gulaman" },
    { top: "Palawan", phrase: "Palawan Island" },
    { top: "Cebu", phrase: "Cebu Island" },
    { top: "Baguio", phrase: "Baguio City" },
    { top: "Davao", phrase: "Davao City" },
    { top: "Intramuros", phrase: "Intramuros Wall" },
    { top: "Hills", phrase: "Chocolate Hills" },
    { top: "Mayon", phrase: "Mayon Volcano" },
    { top: "Taal", phrase: "Taal Volcano" },
    { top: "Banaue", phrase: "Banaue Rice Terraces" },
    { top: "Vigan", phrase: "Vigan City" },
    { top: "Bay", phrase: "Manila Bay" },
    { top: "Bay", phrase: "Subic Bay" },
    { top: "Park", phrase: "Rizal Park" },
    { top: "Park", phrase: "Luneta Park" },
    { top: "Salonga", phrase: "Lea Salonga" },
    { top: "Rizal", phrase: "Jose Rizal" },
    { top: "Bonifacio", phrase: "Andres Bonifacio" },
    { top: "Lapu", phrase: "Lapu Lapu" },
    { top: "Ganda", phrase: "Vice Ganda" },
    { top: "Aquino", phrase: "Kris Aquino" },
    { top: "Aquino", phrase: "Cory Aquino" },
    { top: "Marcos", phrase: "Ferdinand Marcos" },
    { top: "Darna", phrase: "Darna Superhero" },
    { top: "Salamat", phrase: "Salamat Po" },
    { top: "Ano", phrase: "Ano Ba" },
    { top: "Sige", phrase: "Sige Na" },
    { top: "Tara", phrase: "Tara Na" },
    { top: "Ingat", phrase: "Ingat Ka" },
    { top: "Diskarte", phrase: "Diskarte Mo" },
    { top: "Bahala", phrase: "Bahala Ka" },
    { top: "Araw", phrase: "Araw Araw" },
    { top: "Gising", phrase: "Gising Na" },
    { top: "Tulog", phrase: "Tulog Na" },
    { top: "Kain", phrase: "Kain Tayo" },
    { top: "Utang", phrase: "Utang Na Loob" },
    { top: "Pasalubong", phrase: "Pasalubong Gift" },
    { top: "Bayanihan", phrase: "Bayanihan Spirit" },
    { top: "Sayang", phrase: "Sayang Naman" },
    { top: "Grabe", phrase: "Grabe Ka" },
    { top: "Ganda", phrase: "Ganda Mo" },
    { top: "Astig", phrase: "Astig Ka" },
    { top: "Manok", phrase: "Lechon Manok" }
  ],
  "Out of This World": [
    { top: "Belt", phrase: "Asteroid Belt" },
    { top: "Bang", phrase: "Big Bang" },
    { top: "Hole", phrase: "Black Hole" },
    { top: "Way", phrase: "Milky Way" },
    { top: "System", phrase: "Solar System" },
    { top: "Star", phrase: "Neutron Star" },
    { top: "Belt", phrase: "Kuiper Belt" },
    { top: "Hole", phrase: "Worm Hole" },
    { top: "Storm", phrase: "Solar Storm" },
    { top: "Wind", phrase: "Solar Wind" },
    { top: "Flare", phrase: "Solar Flare" },
    { top: "Eclipse", phrase: "Lunar Eclipse" },
    { top: "Landing", phrase: "Moon Landing" },
    { top: "Rover", phrase: "Mars Rover" },
    { top: "Nebula", phrase: "Crab Nebula" },
    { top: "Cluster", phrase: "Star Cluster" },
    { top: "Dwarf", phrase: "Red Dwarf" },
    { top: "Giant", phrase: "Red Giant" },
    { top: "Comet", phrase: "Halley's Comet" },
    { top: "Shower", phrase: "Meteor Shower" },
    { top: "Crater", phrase: "Impact Crater" },
    { top: "Rings", phrase: "Saturn Rings" },
    { top: "Radiation", phrase: "Radiation Belt" },
    { top: "Suit", phrase: "Space Suit" },
    { top: "Walk", phrase: "Space Walk" },
    { top: "Station", phrase: "Space Station" },
    { top: "Pad", phrase: "Launch Pad" },
    { top: "Booster", phrase: "Rocket Booster" },
    { top: "Gravity", phrase: "Zero Gravity" },
    { top: "Orbit", phrase: "Earth Orbit" },
    { top: "Galaxy", phrase: "Spiral Galaxy" },
    { top: "Universe", phrase: "Parallel Universe" },
    { top: "Dust", phrase: "Cosmic Dust" },
    { top: "Ray", phrase: "Cosmic Ray" },
    { top: "Horizon", phrase: "Event Horizon" },
    { top: "Eclipse", phrase: "Solar Eclipse" },
    { top: "Eclipse", phrase: "Total Eclipse" },
    { top: "Moon", phrase: "Blue Moon" },
    { top: "Moon", phrase: "Harvest Moon" },
    { top: "Moon", phrase: "Super Moon" },
    { top: "Planet", phrase: "Dwarf Planet" },
    { top: "Giant", phrase: "Gas Giant" },
    { top: "Giant", phrase: "Ice Giant" },
    { top: "Nebula", phrase: "Ring Nebula" },
    { top: "Nebula", phrase: "Orion Nebula" },
    { top: "Andromeda", phrase: "Andromeda Galaxy" },
    { top: "Galaxy", phrase: "Dwarf Galaxy" },
    { top: "Space", phrase: "Deep Space" },
    { top: "Space", phrase: "Outer Space" },
    { top: "Debris", phrase: "Space Debris" },
    { top: "Panel", phrase: "Solar Panel" },
    { top: "Satellite", phrase: "Satellite Dish" },
    { top: "Satellite", phrase: "Weather Satellite" },
    { top: "Junk", phrase: "Space Junk" },
    { top: "Fuel", phrase: "Rocket Fuel" },
    { top: "Engine", phrase: "Rocket Engine" },
    { top: "Propulsion", phrase: "Jet Propulsion" },
    { top: "Shuttle", phrase: "Space Shuttle" },
    { top: "Module", phrase: "Lunar Module" },
    { top: "Module", phrase: "Command Module" },
    { top: "Control", phrase: "Mission Control" },
    { top: "Control", phrase: "Ground Control" },
    { top: "Countdown", phrase: "Countdown Clock" },
    { top: "Off", phrase: "Blast Off" },
    { top: "Velocity", phrase: "Escape Velocity" },
    { top: "Year", phrase: "Light Year" },
    { top: "Warp", phrase: "Time Warp" },
    { top: "Time", phrase: "Space Time" },
    { top: "Jump", phrase: "Wormhole Jump" },
    { top: "Spaceship", phrase: "Alien Spaceship" },
    { top: "Abduction", phrase: "Alien Abduction" },
    { top: "Saucer", phrase: "Flying Saucer" },
    { top: "Green", phrase: "Little Green Men" },
    { top: "Martian", phrase: "Martian Life" },
    { top: "Planet", phrase: "Red Planet" },
    { top: "Planet", phrase: "Blue Planet" },
    { top: "Planet", phrase: "Ringed Planet" },
    { top: "Cloud", phrase: "Gas Cloud" },
    { top: "Dust", phrase: "Star Dust" },
    { top: "Trail", phrase: "Stardust Trail" },
    { top: "Pulsar", phrase: "Pulsar Star" },
    { top: "Quasar", phrase: "Quasar Light" },
    { top: "Supernova", phrase: "Supernova Blast" },
    { top: "Dwarf", phrase: "White Dwarf" },
    { top: "Dwarf", phrase: "Black Dwarf" },
    { top: "Star", phrase: "Binary Star" },
    { top: "Comet", phrase: "Shooting Comet" },
    { top: "Comet", phrase: "Ice Comet" },
    { top: "Corona", phrase: "Solar Corona" },
    { top: "Field", phrase: "Magnetic Field" },
    { top: "Well", phrase: "Gravity Well" },
    { top: "Probe", phrase: "Space Probe" },
    { top: "Probe", phrase: "Voyager Probe" },
    { top: "Lens", phrase: "Telescope Lens" },
    { top: "Telescope", phrase: "Space Telescope" },
    { top: "Telescope", phrase: "Radio Telescope" },
    { top: "Map", phrase: "Star Map" },
    { top: "Map", phrase: "Constellation Map" },
    { top: "Dipper", phrase: "Big Dipper" },
    { top: "Star", phrase: "North Star" }
  ],
  "Songs": [
    { top: "Rhapsody", phrase: "Bohemian Rhapsody" },
    { top: "California", phrase: "Hotel California" },
    { top: "Rain", phrase: "Purple Rain" },
    { top: "Alabama", phrase: "Sweet Home Alabama" },
    { top: "Queen", phrase: "Dancing Queen" },
    { top: "Jean", phrase: "Billie Jean" },
    { top: "Funk", phrase: "Uptown Funk" },
    { top: "Deep", phrase: "Rolling in the Deep" },
    { top: "Off", phrase: "Shake It Off" },
    { top: "You", phrase: "Someone Like You" },
    { top: "Birthday", phrase: "Happy Birthday" },
    { top: "Twinkle", phrase: "Twinkle Twinkle" },
    { top: "MacDonald", phrase: "Old MacDonald" },
    { top: "Bells", phrase: "Jingle Bells" },
    { top: "Night", phrase: "Silent Night" },
    { top: "Clock", phrase: "Rock Around the Clock" },
    { top: "Submarine", phrase: "Yellow Submarine" },
    { top: "Jude", phrase: "Hey Jude" },
    { top: "Be", phrase: "Let It Be" },
    { top: "Ball", phrase: "Wrecking Ball" },
    { top: "Romance", phrase: "Bad Romance" },
    { top: "Face", phrase: "Poker Face" },
    { top: "Style", phrase: "Gangnam Style" },
    { top: "Maybe", phrase: "Call Me Maybe" },
    { top: "Shape", phrase: "Shape of You" },
    { top: "Space", phrase: "Blank Space" },
    { top: "Caroline", phrase: "Sweet Caroline" },
    { top: "Man", phrase: "Piano Man" },
    { top: "Pie", phrase: "American Pie" },
    { top: "Road", phrase: "Old Town Road" },
    { top: "Run", phrase: "Born to Run" },
    { top: "Champions", phrase: "We Are the Champions" },
    { top: "Tiger", phrase: "Eye of the Tiger" },
    { top: "Dreams", phrase: "Sweet Dreams" },
    { top: "Sun", phrase: "House of the Rising Sun" },
    { top: "Dog", phrase: "Hound Dog" },
    { top: "Shoes", phrase: "Blue Suede Shoes" },
    { top: "Fire", phrase: "Great Balls of Fire" },
    { top: "Heaven", phrase: "Stairway to Heaven" },
    { top: "Bird", phrase: "Free Bird" },
    { top: "Wall", phrase: "Another Brick in the Wall" },
    { top: "Rock", phrase: "We Will Rock You" },
    { top: "Love", phrase: "Somebody to Love" },
    { top: "Me", phrase: "Take On Me" },
    { top: "Mine", phrase: "Sweet Child of Mine" },
    { top: "Spirit", phrase: "Smells Like Teen Spirit" },
    { top: "Sandman", phrase: "Enter Sandman" },
    { top: "Highway", phrase: "Highway to Hell" },
    { top: "Black", phrase: "Back in Black" },
    { top: "Road", phrase: "Thunder Road" },
    { top: "Georgia", phrase: "Midnight Train to Georgia" },
    { top: "Girl", phrase: "Uptown Girl" },
    { top: "Girl", phrase: "Material Girl" },
    { top: "Prayer", phrase: "Like a Prayer" },
    { top: "Fun", phrase: "Girls Just Want to Have Fun" },
    { top: "Survive", phrase: "I Will Survive" },
    { top: "Dark", phrase: "Dancing in the Dark" },
    { top: "Beat", phrase: "Beat It" },
    { top: "Thriller", phrase: "Thriller Night" },
    { top: "Mirror", phrase: "Man in the Mirror" },
    { top: "Guy", phrase: "Bad Guy" },
    { top: "Roads", phrase: "Country Roads" },
    { top: "Fire", phrase: "Ring of Fire" },
    { top: "Country", phrase: "Country Girl" },
    { top: "Places", phrase: "Friends in Low Places" },
    { top: "Perfect", phrase: "Perfect Duet" },
    { top: "Me", phrase: "All of Me" },
    { top: "Loud", phrase: "Thinking Out Loud" },
    { top: "Stars", phrase: "Counting Stars" },
    { top: "Vida", phrase: "Viva la Vida" },
    { top: "You", phrase: "Fix You" },
    { top: "Scientist", phrase: "The Scientist" },
    { top: "Cars", phrase: "Chasing Cars" },
    { top: "Somebody", phrase: "Use Somebody" },
    { top: "Fire", phrase: "Sex on Fire" },
    { top: "Brightside", phrase: "Mr Brightside" },
    { top: "Know", phrase: "Somebody That I Used to Know" },
    { top: "Rain", phrase: "Set Fire to the Rain" },
    { top: "Man", phrase: "When I Was Your Man" },
    { top: "Way", phrase: "Just the Way You Are" },
    { top: "Heaven", phrase: "Locked Out of Heaven" },
    { top: "Me", phrase: "Count On Me" },
    { top: "Horse", phrase: "Dark Horse" },
    { top: "Girls", phrase: "California Girls" },
    { top: "Dream", phrase: "Teenage Dream" },
    { top: "Awake", phrase: "Wide Awake" },
    { top: "Anthem", phrase: "Party Rock Anthem" },
    { top: "Know", phrase: "Sexy and I Know It" },
    { top: "Feeling", phrase: "I Gotta Feeling" },
    { top: "Vibrations", phrase: "Good Vibrations" },
    { top: "Sunshine", phrase: "Walking on Sunshine" },
    { top: "Mia", phrase: "Mamma Mia" },
    { top: "Trouper", phrase: "Super Trouper" },
    { top: "Money", phrase: "Money Money Money" },
    { top: "Knowing", phrase: "Knowing Me Knowing You" },
    { top: "Chance", phrase: "Take a Chance on Me" },
    { top: "Blood", phrase: "Bad Blood" },
    { top: "Lights", phrase: "Blinding Lights" },
    { top: "Sugar", phrase: "Watermelon Sugar" },
    { top: "License", phrase: "Drivers License" }
  ]
};
